config/routes.rb
Rails.application.routes.draw do

  namespace :admin do

    get 'login' => 'user_sessions#new', :as => 'login'
    get 'badges' => 'dashboard#badges'

    resources :password_resets, :only => [:index, :create, :show, :update], :path => 'login/forgot'

    get 'settings' => 'settings#edit', :as => 'settings'
    put 'settings' => 'settings#update'
    put 'change_sort' => 'dashboard#change_sort'

    root :to => "dashboard#index", as: :root
    resources :users do
      get 'export', :on => :collection
    end
    resources :roles

    get 'setup' => 'setup#new'
    post 'setup' => 'setup#create'
  end

  # Non-admin login paths
  get 'login' => 'user_sessions#new', :as => 'login'
  post 'login' => 'user_sessions#create'
  match 'logout' => 'user_sessions#destroy', :as => 'logout', :via => [:get, :post]

  get 'login/change_password' => 'user_sessions#change_password'
  post 'login/change_password' => 'user_sessions#set_change_password'

  resources :password_resets, :only => [:index, :create, :show, :update], :path => 'login/forgot'

  get 'spud/admin' => 'admin/user_sessions#legacy_redirect'
  get 'tb_core/not_found' => 'tb_core/application#not_found', as: 'not_found' unless Rails.env.production?

end

app/views/layouts/admin/_flashes.html.erb
<% if flash[:notice] %>
    <div class="alert alert-success">
      <a class="close" data-dismiss="alert">×</a>
      <%= flash[:notice] %>
    </div>
  <% end %>
  <% if flash[:warning] %>
    <div class="alert alert-warning">
      <a class="close" data-dismiss="alert">×</a>
      <%= flash[:warning] %>
    </div>
  <% end %>
  <% if flash[:error]%>
  <div class="alert alert-error">
      <a class="close" data-dismiss="alert">×</a>
      <%= flash[:error] %>
  </div>
  <% end %>
  

app/views/layouts/admin/_search.html.erb
<%= form_tag search_path, :method => :get, :class => 'form-inline admin-search-form' do %>
  <div class="form-group">
    <div class="input-group">
      <div class="input-group-addon"><span class="glyphicon glyphicon-search"></span></div>
      <%= search_field_tag :search, params[:search], :placeholder => 'Search', :class => 'form-control' %>
      <% if params[:search] %>
        <div class="input-group-addon">
          <%= link_to raw('<span class="glyphicon glyphicon-remove"></span>'), search_path %>
        </div>
      <% end %>
      <% if params[:tab] %>
        <%= hidden_field_tag :tab, params[:tab] %>
      <% end %>
    </div>
  </div>
<% end %>

app/views/layouts/admin/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <title><%= TbCore.config.site_name %> Admin</title>
  <%= tinymce_assets unless ENV['TB_SKIP_TINYMCE'] %>
  <%= stylesheet_link_tag *TbCore.config.admin_stylesheets %>
  <%= javascript_include_tag *TbCore.config.admin_javascripts %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="viewport" content="width=device-width"/>
  <%= yield :head %>
</head>
<body>
<% if TbCore.production_alert_domain %>
  <div class="production-alert-header">
    <p><strong>Notice:</strong> This is a staging version of your website. To update your live website, please <%= link_to 'log in to production.', "http://#{TbCore.production_alert_domain}/admin" %></p>
  </div>
<% end %>
<div id="header">
  <div class="container">
  	<%= link_to '/' do %>
      <h1><%= TbCore.config.site_name %></h1>
    <% end %>
    <% if current_user %>
    	<div class="pull-right">
    		Hello <%= current_user.full_name %> |
        <%= link_to "Settings", admin_settings_path %> |
        <%= link_to "Logout", logout_path(:return_to => admin_login_path) %>
    	</div>
    <% end %>
  </div>
</div>

<div class="container">

  <ol class="breadcrumb">
    <%= render_breadcrumbs :tag => :li, :separator => "" %>
  </ol>

  <%= render :partial => '/layouts/admin/flashes' %>

  <%= content_for?(:content) ? yield(:content) : yield %>
</div>

<div class="modal fade" id="modal_window">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h3 class="modal-title"></h3>
      </div>
      <div class="modal-body">
        <p>...</p>
      </div>
      <div class="modal-footer modal-footer-default">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        <button type="button" class="btn btn-primary form-submit">Save changes</button>
      </div>
    </div>
  </div>
</div>


</body>
</html>

app/views/layouts/admin/detail.html.erb
<%= content_for :content do %>
  <div class="detail-wrapper">
    <div class="data-controls">
      <%= yield :data_controls %>
    </div>
    <h2 class="detail-title">
      <% if @page_thumbnail %>
        <%= image_tag(@page_thumbnail, :class => 'app-thumbnail') %>
      <% end %>
      <%= @page_name %>
    </h2>
    <div class="details">
      <%= content_for?(:detail) ? yield(:detail) : yield %>
    </div>
  </div>
<% end %>
<%= render :template => 'layouts/admin/application' %>

app/views/layouts/admin/error_page.html.erb
<% @page_name = "#{@error.code}: #{@error.title}!" %>

<%= content_for :detail do %>
  <p><%= @error.message %></p>
  <% if @error.code == 403 %>
    <p>Your user might not have admin rights, or you might be trying to access a module that you have not been granted permission to.</p>
  <% end %>
  <p>Requested URL: <%= @error.request_url %></p>
<% end %>

<%= render :template => 'layouts/admin/detail' %>

app/views/layouts/admin/login.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= TbCore.config.site_name %> Admin: Login</title>
  <%= stylesheet_link_tag 'admin/core/application' %>
  <%= javascript_include_tag 'admin/core/application' %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="viewport" content="width=device-width"/>
</head>
<body>

<div class="container">
  <div class="login-container col-md-6 col-md-offset-3">
    <h1><%= @login_title || 'Login' %></h1>
    <%= yield %>
  </div>
</div>

</body>
</html>