config/routes.rb
Rails.application.routes.draw do

  namespace :admin do

    get 'login' => 'user_sessions#new', :as => 'login'
    get 'badges' => 'dashboard#badges'

    resources :password_resets, :only => [:index, :create, :show, :update], :path => 'login/forgot'

    get 'settings' => 'settings#edit', :as => 'settings'
    put 'settings' => 'settings#update'
    put 'change_sort' => 'dashboard#change_sort'

    root :to => "dashboard#index", as: :root
    resources :users do
      get 'export', :on => :collection
    end
    resources :roles

    get 'setup' => 'setup#new'
    post 'setup' => 'setup#create'
  end

  # Non-admin login paths
  get 'login' => 'user_sessions#new', :as => 'login'
  post 'login' => 'user_sessions#create'
  match 'logout' => 'user_sessions#destroy', :as => 'logout', :via => [:get, :post]

  get 'login/change_password' => 'user_sessions#change_password'
  post 'login/change_password' => 'user_sessions#set_change_password'

  resources :password_resets, :only => [:index, :create, :show, :update], :path => 'login/forgot'

  get 'spud/admin' => 'admin/user_sessions#legacy_redirect'
  get 'tb_core/not_found' => 'tb_core/application#not_found', as: 'not_found' unless Rails.env.production?

end

app/controllers/admin/roles_controller.rb
class Admin::RolesController < Admin::ApplicationController

  before_action :get_record, only: [:show, :edit, :update, :destroy]
  respond_to :html, :json, :xml
  belongs_to_app :users
  add_breadcrumb 'Users', :admin_users_path
  add_breadcrumb 'Roles', :admin_roles_path

  def index
    @roles = SpudRole.includes(:spud_role_permissions)
    respond_with @roles
  end
  
  def show
    respond_with @role
  end
  
  def new
    @role = SpudRole.new
    respond_with @role
  end
  
  def create
    logger.debug 'role_params:'
    logger.debug role_params
    @role = SpudRole.new(role_params)
    flash[:notice] = 'SpudRole created successfully' if @role.save
    respond_with @role, location: admin_roles_path
  end
  
  def edit
    respond_with @role
  end
  
  def update
    #role_params[:permission_tags] ||= []
    flash[:notice] = 'SpudRole updated successfully' if @role.update(role_params)
    respond_with @role, location: admin_roles_path
  end
  
  def destroy
    flash[:notice] = 'SpudRole deleted successfully' if @role.destroy
    respond_with @role, location: admin_roles_path
  end

  private

  def get_record
    begin
      @role = SpudRole.find(params[:id])
    rescue ActiveRecord::RecordNotFound => e
      flash[:error] = 'Could not find the requested SpudRole'
      redirect_to admin_roles_path
      return false
    end
  end

  def role_params
    params.require(:spud_role).permit(:name, permission_tags: [])
  end

end

app/helpers/admin/roles_helper.rb
module Admin::RolesHelper
end

app/views/admin/roles/_form.html.erb
<%= form_for @role, :url => path, :html => {:class => 'form-horizontal'} do |f| %>
  
  <div class="form-group">
    <%= f.label :name, :required => true, :class => "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :name, :title => "", :class => 'form-control'%>
    </div>
  </div>

  <div class="form-group">
    <%= label_tag :permissions, 'Permissions', :required => true, :class => "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <% SpudPermission.sorted_by_tag.each do |permission| %>
        <div class="checkbox">
          <label>
            <%= check_box_tag 'spud_role[permission_tags][]', permission.tag, @role.permissions.include?(permission) %>
            <%= permission.name %>
          </label>
        </div>
      <% end %>
    </div>
  </div>

  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit "Save Role", :class=>"btn btn-primary", "data-loading-text" => "Saving..." %> 
      <%= link_to "Cancel", admin_roles_path, :class => "btn btn-default" %>
    </div>
  </div>

<% end %>

app/views/admin/roles/edit.html.erb
<% @page_name = 'Edit Role' %>
<%= render :partial => 'form', :locals => {:path => admin_role_path(@role)} %>

app/views/admin/roles/index.html.erb
<% @page_name = 'Roles' %>

<%= content_for :data_controls do %>
  <%= link_to 'New Role', new_admin_role_path, :class => 'btn btn-primary' %>
<% end %>

<% content_for :detail do %>
  <div class="table-responsive">
    <table class="table table-striped table-hover">
      <thead>
        <tr>
          <th>Name</th>
          <th># Users</th>
          <th>Permissions</th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        <% @roles.each do |role| %>
          <tr>
            <td><%= role.name %></td>
            <td><%= role.users.count %></td>
            <td><%= role.permissions.collect(&:name).join(', ') %></td>
            <td align="right">
              <%= link_to 'Edit', edit_admin_role_path(role), :class => 'btn btn-sm btn-default' %>
              <%= link_to 'Delete', admin_role_path(role), :method => :delete, :data => {:confirm => 'Are you sure?'}, :class => 'btn btn-sm btn-danger' %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
<% end %>

app/views/admin/roles/new.html.erb
<% @page_name = 'New Role' %>
<%= render :partial => 'form', :locals => {:path => admin_roles_path} %>