config/routes.rb
Rails.application.routes.draw do

  namespace :admin do

    get 'login' => 'user_sessions#new', :as => 'login'
    get 'badges' => 'dashboard#badges'

    resources :password_resets, :only => [:index, :create, :show, :update], :path => 'login/forgot'

    get 'settings' => 'settings#edit', :as => 'settings'
    put 'settings' => 'settings#update'
    put 'change_sort' => 'dashboard#change_sort'

    root :to => "dashboard#index", as: :root
    resources :users do
      get 'export', :on => :collection
    end
    resources :roles

    get 'setup' => 'setup#new'
    post 'setup' => 'setup#create'
  end

  # Non-admin login paths
  get 'login' => 'user_sessions#new', :as => 'login'
  post 'login' => 'user_sessions#create'
  match 'logout' => 'user_sessions#destroy', :as => 'logout', :via => [:get, :post]

  get 'login/change_password' => 'user_sessions#change_password'
  post 'login/change_password' => 'user_sessions#set_change_password'

  resources :password_resets, :only => [:index, :create, :show, :update], :path => 'login/forgot'

  get 'spud/admin' => 'admin/user_sessions#legacy_redirect'
  get 'tb_core/not_found' => 'tb_core/application#not_found', as: 'not_found' unless Rails.env.production?

end

app/controllers/admin/users_controller.rb
class Admin::UsersController < Admin::ApplicationController
  require 'csv'

  belongs_to_app :users
  add_breadcrumb 'Users', :admin_users_path
  before_action :load_user, only: [:edit, :update, :show, :destroy]
  after_action :send_credentials_email, only: [:create, :update]
  respond_to :html, :csv

  sortable_by :email, :current_login_at,
    name: [:last_name, :first_name],
    default: :email

  def index
    @spud_users = SpudUser.order(sortable_query).paginate(page: params[:page], per_page: 15)
    if params[:search]
      @spud_users = @spud_users.where_name_like(params[:search])
    end
    respond_with @spud_users
  end

  def show
    respond_with @user
  end

  def export
    users = SpudUser.all
    export_columns = %w[created_at first_name last_name email last_login_at]
    file_name = TbCore.site_name + ' Users Export.csv'
    send_data users.as_csv(export_columns),
      type: 'text/csv; charset=iso-8859-1; header=present',
      disposition: "attachment; filename=#{file_name}"
  end

  def new
    @user = SpudUser.new
    respond_with @user do |format|
      format.html{
        if request.xhr?
          render 'new', layout: false
        else
          render 'new'
        end
      }
    end
  end

  def create
    @user = SpudUser.create(user_params)
    respond_with @user, location: admin_users_path
  end

  def edit
    respond_with @user do |format|
      format.html{
        if request.xhr?
          render 'edit', layout: false
        else
          render 'edit'
        end
      }
    end
  end

  def update
    if @user.update(user_params)
      if @user == current_user && user_params[:password].present?
        SpudUserSession.create(@user)
      end
    end
    respond_with @user, location: admin_user_path(@user), status: 200
  end

  def destroy
    @user.destroy
    respond_with @user, location: admin_users_path do |format|
      format.js{
        render nothing: true, status: :ok
      }
    end
  end

private

  def load_user
    @user = SpudUser.find_by!(id: params[:id])
  end

  def user_params
    params.require(:spud_user).permit!
  end

  def send_credentials_email
    if params[:send_email] && user_params[:password] && @user.errors.none?
      TbCoreMailer.user_credentials(@user, user_params[:password]).deliver_later
    end
    return true
  end

end

app/views/admin/users/_form.html.erb
<%= tb_form_for @user, :url => path, :remote => true, :data => {:errors => :inline, :success => back_or_default(admin_users_path)}, :html => {:class => 'user-form'} do |f| %>

  <%= tb_form_error_header(f.object) %>

  <%= f.tb_sub_title 'User Details' %>

  <% if !TbCore.config.use_email_as_login %>
    <%= f.tb_text_field :login %>
  <% end %>
  <%= f.tb_text_field :email %>
  <%= f.tb_text_field :first_name %>
  <%= f.tb_text_field :last_name %>
  <%= f.tb_time_zone_select :time_zone, ActiveSupport::TimeZone.us_zones, {:default => Rails.application.config.time_zone} %>

  <%= render :partial => 'form_additions', :locals => {:f => f} %>

  <%= f.tb_sub_title 'Credentials' %>

  <%= f.tb_password_field :password %>
  <%= f.tb_password_field :password_confirmation %>

  <div class="form-group">
    <div class="col-sm-10 col-sm-offset-2">
      <%= link_to 'Generate Password', '#', :class => 'btn btn-default btn-sm btn-generate-password' %>
      <span class="generated-password text-success"></span>
    </div>
  </div>

  <div class="form-group">
    <%= f.tb_label :requires_password_change %>
    <div class="col-sm-10">
      <%= f.check_box :requires_password_change %>
      <span class="text-muted">Require the user changes their password the next time they log in.</span>
    </div>
  </div>

  <div class="form-group user-send-email-group">
    <%= label_tag :send_email, 'Send email', :class => 'control-label col-sm-2' %>
    <div class="col-sm-10">
      <%= check_box_tag :send_email %>
      <span class="text-muted">Send the user an email containing their password.</span>
    </div>
  </div>

  <%= f.tb_sub_title 'Permissions' %>

  <%= f.tb_check_box :super_admin, :help_block => 'The super administrator bypasses all permissions and roles.' %>
  <%= f.tb_select :spud_role_id, options_from_collection_for_select(SpudRole.all, :id, :name, f.object.spud_role_id), {:include_blank => 'No Role'} %>

  <%= f.tb_save_buttons('User', @user.new_record? ? admin_users_path : admin_user_path(@user)) %>

<% end %>

app/views/admin/users/_form_additions.html.erb
<!-- Copy me to your application to add custom fields to the New/Edit action -->

app/views/admin/users/_show_additions.html.erb
<!-- Copy me to your application to add custom fields to the Show action -->

app/views/admin/users/edit.html.erb
<%= render :partial => "form", :locals => {:path => admin_user_path(@user)} %>

app/views/admin/users/index.html.erb
<%= content_for :data_controls do %>
  <%= render :partial => '/layouts/admin/search', :locals => {:search_path => admin_users_path} %>
  <%= link_to 'Roles', admin_roles_path, :class => 'btn btn-default admin-role-btn' %>
  <%= link_to "New User", new_admin_user_path, :class => "btn btn-primary admin-user-add-btn", :title => "New User" %>
  <%= link_to "Export", export_admin_users_path, :class => "btn btn-primary admin-user-add-btn", :title => "New User" %>
<% end %>

<%= content_for :detail do %>
  <div class="table-responsive">
    <table class="table table-striped table-hover">
      <%= sortable_table_header :admin_users_path, model: SpudUser do |t| %>
        <%= t.sortable :name %>
        <%= t.sortable :email %>
        <%= t.sortable :current_login_at %>
        <th></th>
      <% end %>
      <tbody>
        <% @spud_users.each do |spud_user| %>
          <tr>
            <td><%= spud_user.full_name %></td>
            <td><%= mail_to spud_user.email %></td>
            <td><%= timestamp spud_user.current_login_at %></td>
            <td class="table-actions">
              <%= link_to 'Details', admin_user_path(spud_user), :class => 'btn btn-default btn-sm' %>
              <%= link_to 'Edit', edit_admin_user_path(spud_user), :class => 'btn btn-default btn-sm' %>
              <%= link_to 'Delete', admin_user_path(spud_user), :method => :delete, :data => {:confirm => 'Are you sure you want to delete this user?'}, :class => 'btn btn-danger btn-sm' %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>

  <%= will_paginate @spud_users, :renderer => BootstrapPagination::Rails %>

  <script>
    document.addEventListener('DOMContentLoaded', tb.users.index);
  </script>
<% end %>

app/views/admin/users/new.html.erb
<%= render :partial => "form", :locals => {:path => admin_users_path} %>

app/views/admin/users/show.html.erb
<%= content_for :data_controls do %>
  <%= link_to 'Edit', edit_admin_user_path(@user), :class => 'btn btn-primary admin-user-edit-btn', :title => "Edit" %>
<% end %>

<dl class="dl-horizontal">
  <% if !TbCore.config.use_email_as_login %>
    <dt>Login</dt>
    <dd><%= @user.login %></dd>
  <% end %>
  <dt>Email</dt>
  <dd><%= mail_to @user.email %></dd>
  <dt>Last Login</dt>
  <dd><%= timestamp @user.current_login_at %></dd>
  <dt>Created At</dt>
  <dd><%= timestamp @user.created_at %></dd>
  <dt>Role:</dt>
  <dd><%= @user.role.blank? ? 'None' : @user.role.name %></dd>
  <dt>Super Admin?<dt>
  <dd><%= @user.super_admin? ? 'Yes' : 'No' %></dd>
  <%= render 'show_additions' %>
</dl>