config/routes.rb
Rails.application.routes.draw do

  namespace :admin do

    get 'login' => 'user_sessions#new', :as => 'login'
    get 'badges' => 'dashboard#badges'

    resources :password_resets, :only => [:index, :create, :show, :update], :path => 'login/forgot'

    get 'settings' => 'settings#edit', :as => 'settings'
    put 'settings' => 'settings#update'
    put 'change_sort' => 'dashboard#change_sort'

    root :to => "dashboard#index", as: :root
    resources :users do
      get 'export', :on => :collection
    end
    resources :roles

    get 'setup' => 'setup#new'
    post 'setup' => 'setup#create'
  end

  # Non-admin login paths
  get 'login' => 'user_sessions#new', :as => 'login'
  post 'login' => 'user_sessions#create'
  match 'logout' => 'user_sessions#destroy', :as => 'logout', :via => [:get, :post]

  get 'login/change_password' => 'user_sessions#change_password'
  post 'login/change_password' => 'user_sessions#set_change_password'

  resources :password_resets, :only => [:index, :create, :show, :update], :path => 'login/forgot'

  get 'spud/admin' => 'admin/user_sessions#legacy_redirect'
  get 'tb_core/not_found' => 'tb_core/application#not_found', as: 'not_found' unless Rails.env.production?

end

app/controllers/admin/user_sessions_controller.rb
class Admin::UserSessionsController < Admin::ApplicationController

  skip_before_action :require_admin_user
  layout 'admin/login'

  def new
    if current_user
      redirect_to admin_root_path
    elsif SpudUser.all.count.zero?
      logger.debug 'NO USERS!'
      redirect_to admin_setup_path and return
    end
    @user_session = SpudUserSession.new
  end

  def legacy_redirect
    redirect_to admin_login_path
  end

end

app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController

  skip_before_action :require_user, only: [:new, :create, :destroy], raise: false
  skip_before_action :check_requires_password_change,
    only: [:destroy, :change_password, :set_change_password],
    raise: false

  respond_to :html, :json, :js
  layout 'user_sessions'

  def new
    @user_session = SpudUserSession.new
    render 'new'
  end

  def create
    @user_session = SpudUserSession.new(user_session_params.to_h)
    if @user_session.save()
      respond_with @user_session do |format|
        format.html{
          flash[:notice] = 'Login successful!'
          redirect_back_or_default('/')
        }
        format.json{
          render json: {success: true}
        }
      end
    else
      respond_with @user_session do |format|
        format.html{
          render 'new'
        }
      end
    end
  end

  def destroy
    current_user_session.destroy if current_user_session.present?
    respond_with({}) do |format|
      format.html{
        flash[:notice] = 'Logout successful!'
        redirect_back_or_default(login_path)
      }
    end
  end

  def change_password
    require_user
    render 'change_password'
  end

  def set_change_password
    current_user.update(change_password_params)
    respond_with current_user do |format|
      format.html{
        if current_user.errors.any?
          render 'change_password'
        else
          redirect_back_or_default('/')
        end
      }
    end
  end

private

  def user_session_params
    params.require(:spud_user_session).permit(:login, :password, :email)
  end

  def change_password_params
    params.require(:spud_user).permit(:password, :password_confirmation)
  end

end

app/views/user_sessions/_form.html.erb
<% @user_session ||= SpudUserSession.new %>
<% return_to = '/' if local_assigns[:return_to].nil? %>

<%= form_for @user_session, :url => login_path, :html => {:class => 'login-form'}, :remote => true, :data => {:success => back_or_default(return_to), :errors => :inline} do |f| %>
  <%= tb_form_errors(@user_session) %>
  <%= hidden_field_tag :return_to, return_to %>
  <div class="form-group">
    <% if TbCore.config.use_email_as_login %>
      <%= f.label :email %>
      <%= f.text_field :email, :placeholder => 'Email', :autofocus => 'autofocus', :autocomplete => 'username', :class => 'form-control' %>
    <% else %>
      <%= f.label :login %>
      <%= f.text_field :login, :placeholder => 'Username', :autofocus => 'autofocus', :autocomplete => 'username', :class => 'form-control' %>
    <% end %>
  </div>
  <div class="form-group">
    <%= f.label :password %>
    <%= f.password_field :password, :placeholder => 'Password', :autocomplete => 'current-password', :class => 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.submit "Login", :class => 'btn btn-primary', :data => {:disable_with => 'Logging in...', :enable_with => 'Done!'} %>
    <span>or</span> <%= link_to "Forgot Password?", password_resets_path %>
  </div>
<% end %>

app/views/user_sessions/change_password.html.erb
<% @page_title = 'Login' %>

<h1>Set New Password</h1>

<p>You must set a new password before you may continue.</p>

<%= form_for current_user, :url => login_change_password_path, :method => :post, :remote => true, :data => {:errors => :inline, :success => back_or_default('/')} do |f| %>
  <%= hidden_field_tag :return_to, back_or_default('/') %>
  <%= tb_form_errors(current_user) %>
  <div class="form-group">
    <%= f.label :password %>
    <%= f.password_field :password, :placeholder => 'Password', :class => 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation, :placeholder => 'Password Confirmation', :class => 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.submit 'Set Password', :class => 'btn btn-primary', :data => {:disable_with => 'Setting...', :enable_with => 'Done!'} %>
  </div>
<% end %>

app/views/user_sessions/new.html.erb
<% @page_title = 'Login' %>

<h1><%= TbCore.config.site_name %> Login</h1>

<%= render 'form' %>